"use client";
import { useState } from "react";
import Link from "next/link";
import AppLayout from "@/app/(app)/layout";
import Header from "@/components/layout/Header";
import { mockClients } from "@/lib/mockData";

interface ActionItem { owner: string; action: string; dueDate: string | null; }
interface MeetingSummary {
  summary: string;
  attendees: string[];
  topicsDiscussed: string[];
  decisions: string[];
  actionItems: ActionItem[];
  featureRequests: string[];
  risksRaised: string[];
  nextMeetingSuggested: string | null;
}

const SAMPLE_NOTES = `Meeting: Quarterly Business Review — ABC Retail Group
Date: 28 June 2026
Attendees: Jonathan (URUP), Sarah Mkhize (IT Manager), David Nkosi (CTO), Priya Patel (Project Lead)

Discussion:
- Loyalty programme has been live for 3 months. Redemption rates up 340% vs Q1. Customer feedback very positive.
- David raised concerns about the bulk import process — taking too long for large files (over 10,000 rows). Users are complaining.
- Sarah requested a dashboard improvement: they need to see real-time stock levels alongside loyalty data. Currently two separate systems.
- New requirement: users want to upload profile photos for loyalty cards. Currently text only.
- Budget approved for Q3: R180,000 for new feature development.
- Black Friday 2026 planning needs to start in July. Last year's journey can be reused as baseline.

Decisions:
- Dashboard integration approved. Jonathan to produce SOW by 4 July.
- Bulk import optimisation prioritised — target fix by end of July.
- Profile photo upload added to backlog for Q3.
- Black Friday kick-off meeting scheduled for 10 July.

Actions:
- Jonathan: send SOW for dashboard integration by 4 July
- Jonathan: investigate bulk import performance issue, share findings by 2 July  
- David: provide API documentation for stock system by 7 July
- Sarah: confirm Black Friday campaign brief by 12 July
- Priya: write up profile photo requirements and send to Jonathan`;

export default function MeetingIntelligencePage() {
  const [clientId, setClientId] = useState("1");
  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<MeetingSummary | null>(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const handleAnalyse = async () => {
    if (!notes.trim()) { setError("Please paste meeting notes first."); return; }
    setError("");
    setLoading(true);
    setResult(null);

    try {
      const client = mockClients.find(c => c.id === clientId);
      const systemPrompt = `You are a Client Success assistant. Produce a structured meeting summary from raw meeting notes.

Respond ONLY with valid JSON. No preamble, no markdown, no code fences.

JSON structure:
{
  "summary": "3 to 5 sentence overview",
  "attendees": ["string"],
  "topicsDiscussed": ["string"],
  "decisions": ["string"],
  "actionItems": [
    { "owner": "string", "action": "string", "dueDate": "string or null" }
  ],
  "featureRequests": ["string"],
  "risksRaised": ["string"],
  "nextMeetingSuggested": "string or null"
}`;

      const userPrompt = `Client: ${client?.name || "Unknown"}

Notes:
${notes}

Produce a structured meeting summary.`;

      const response = await fetch("/api/ai", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ system: systemPrompt, user: userPrompt, maxTokens: 1500 }),
      });

      if (!response.ok) throw new Error("AI service error");
      const data = await response.json();
      const clean = data.content.replace(/```json|```/g, "").trim();
      setResult(JSON.parse(clean));
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Analysis failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const buildExport = () => {
    if (!result) return "";
    const client = mockClients.find(c => c.id === clientId);
    let out = `MEETING SUMMARY — ${client?.name || "Client"}\n`;
    out += `Generated by CS Hub | ${new Date().toLocaleDateString("en-ZA")}\n${"─".repeat(60)}\n\n`;
    out += `SUMMARY\n${result.summary}\n\n`;
    if (result.attendees?.length) out += `ATTENDEES\n${result.attendees.join(", ")}\n\n`;
    if (result.decisions?.length) { out += `DECISIONS\n`; result.decisions.forEach(d => { out += `• ${d}\n`; }); out += "\n"; }
    if (result.actionItems?.length) {
      out += `ACTION ITEMS\n`;
      result.actionItems.forEach(a => { out += `• ${a.owner}: ${a.action}${a.dueDate ? ` (by ${a.dueDate})` : ""}\n`; });
      out += "\n";
    }
    if (result.featureRequests?.length) { out += `FEATURE REQUESTS\n`; result.featureRequests.forEach(f => { out += `• ${f}\n`; }); out += "\n"; }
    if (result.risksRaised?.length) { out += `RISKS\n`; result.risksRaised.forEach(r => { out += `• ${r}\n`; }); }
    return out;
  };

  return (
    <AppLayout>
      <Header
        title="Meeting Intelligence"
        subtitle="AI generates structured summaries, decisions, and action items from meeting notes"
        actions={
          <div style={{ display: "flex", gap: 8 }}>
            <Link href="/intelligence"><button className="btn-secondary" style={{ fontSize: 12 }}>Back</button></Link>
            {result && (
              <button className="btn-primary" style={{ fontSize: 12 }} onClick={() => { navigator.clipboard.writeText(buildExport()); setCopied(true); setTimeout(() => setCopied(false), 2500); }}>
                {copied ? "Copied!" : "Copy Summary"}
              </button>
            )}
          </div>
        }
      />

      <div style={{ padding: 24, display: "grid", gridTemplateColumns: result ? "1fr 1fr" : "1fr", gap: 24, maxWidth: result ? "none" : 800, margin: result ? "0" : "0 auto" }}>

        {/* Input */}
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div className="card">
            <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text-primary)", marginBottom: 16, paddingBottom: 10, borderBottom: "1px solid var(--border)" }}>Meeting Notes Input</div>
            <div style={{ marginBottom: 14 }}>
              <label style={{ fontSize: 12, color: "var(--text-secondary)", display: "block", marginBottom: 5 }}>Client</label>
              <select className="input" value={clientId} onChange={e => setClientId(e.target.value)} style={{ background: "var(--bg-elevated)" }}>
                <option value="">Select client...</option>
                {mockClients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
            <div style={{ marginBottom: 14 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 5 }}>
                <label style={{ fontSize: 12, color: "var(--text-secondary)" }}>Meeting Notes or Transcript</label>
                <button onClick={() => setNotes(SAMPLE_NOTES)} style={{ background: "none", border: "none", fontSize: 11, color: "var(--accent-blue)", cursor: "pointer" }}>
                  Load sample notes
                </button>
              </div>
              <textarea className="input" rows={16} style={{ resize: "vertical", fontFamily: "inherit" }}
                placeholder="Paste Teams meeting notes, a transcript, or handwritten notes here..."
                value={notes} onChange={e => setNotes(e.target.value)} />
            </div>
            {error && (
              <div style={{ padding: "10px 14px", background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.3)", borderRadius: 8, fontSize: 13, color: "var(--accent-red)", marginBottom: 12 }}>
                {error}
              </div>
            )}
            <button className="btn-primary" style={{ width: "100%", justifyContent: "center", fontSize: 13, padding: "10px", opacity: loading ? 0.7 : 1 }} onClick={handleAnalyse} disabled={loading}>
              {loading ? "Analysing meeting..." : "Generate Meeting Summary"}
            </button>
          </div>
        </div>

        {/* Results */}
        {result && (
          <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>

            <div style={{ background: "rgba(59,130,246,0.06)", border: "1px solid rgba(59,130,246,0.2)", borderRadius: 12, padding: 16 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: "var(--accent-blue)", marginBottom: 6 }}>AI Summary</div>
              <div style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.7 }}>{result.summary}</div>
            </div>

            {result.attendees?.length > 0 && (
              <div className="card" style={{ padding: "14px 18px" }}>
                <div style={{ fontSize: 12, fontWeight: 600, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 8 }}>Attendees</div>
                <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
                  {result.attendees.map((a, i) => <span key={i} className="badge badge-gray">{a}</span>)}
                </div>
              </div>
            )}

            {result.decisions?.length > 0 && (
              <div className="card" style={{ padding: 0, overflow: "hidden" }}>
                <div style={{ padding: "12px 18px", borderBottom: "1px solid var(--border)", fontSize: 13, fontWeight: 600, color: "var(--text-primary)" }}>
                  Decisions ({result.decisions.length})
                </div>
                {result.decisions.map((d, i) => (
                  <div key={i} style={{ padding: "10px 18px", borderBottom: "1px solid var(--border)", display: "flex", gap: 10, alignItems: "flex-start" }}>
                    <svg width="14" height="14" fill="none" stroke="var(--accent-green)" strokeWidth={2} viewBox="0 0 24 24" style={{ flexShrink: 0, marginTop: 2 }}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{d}</span>
                  </div>
                ))}
              </div>
            )}

            {result.actionItems?.length > 0 && (
              <div className="card" style={{ padding: 0, overflow: "hidden" }}>
                <div style={{ padding: "12px 18px", borderBottom: "1px solid var(--border)", fontSize: 13, fontWeight: 600, color: "var(--text-primary)" }}>
                  Action Items ({result.actionItems.length})
                </div>
                {result.actionItems.map((item, i) => (
                  <div key={i} style={{ padding: "12px 18px", borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", gap: 12 }}>
                    <div style={{
                      width: 32, height: 32, borderRadius: 8, flexShrink: 0,
                      background: "rgba(59,130,246,0.1)",
                      display: "flex", alignItems: "center", justifyContent: "center",
                      fontSize: 11, fontWeight: 700, color: "var(--accent-blue)",
                    }}>
                      {item.owner?.split(" ").map((n: string) => n[0]).join("").slice(0, 2).toUpperCase()}
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 13, fontWeight: 500, color: "var(--text-primary)" }}>{item.action}</div>
                      <div style={{ fontSize: 11, color: "var(--text-muted)" }}>{item.owner}</div>
                    </div>
                    {item.dueDate && (
                      <span className="badge badge-amber" style={{ fontSize: 11 }}>{item.dueDate}</span>
                    )}
                  </div>
                ))}
              </div>
            )}

            {result.featureRequests?.length > 0 && (
              <div className="card" style={{ padding: 0, overflow: "hidden" }}>
                <div style={{ padding: "12px 18px", borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                  <span style={{ fontSize: 13, fontWeight: 600, color: "var(--text-primary)" }}>Feature Requests ({result.featureRequests.length})</span>
                  <Link href="/intelligence/capture">
                    <button className="btn-secondary" style={{ fontSize: 11, padding: "3px 8px" }}>Extract Requirements</button>
                  </Link>
                </div>
                {result.featureRequests.map((f, i) => (
                  <div key={i} style={{ padding: "10px 18px", borderBottom: "1px solid var(--border)", display: "flex", gap: 10 }}>
                    <svg width="14" height="14" fill="none" stroke="var(--accent-purple)" strokeWidth={2} viewBox="0 0 24 24" style={{ flexShrink: 0, marginTop: 2 }}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                    </svg>
                    <span style={{ fontSize: 13, color: "var(--text-secondary)" }}>{f}</span>
                  </div>
                ))}
              </div>
            )}

            {result.risksRaised?.length > 0 && (
              <div className="card">
                <div style={{ fontSize: 12, fontWeight: 600, color: "var(--accent-red)", marginBottom: 8 }}>Risks Raised</div>
                {result.risksRaised.map((r, i) => (
                  <div key={i} style={{ display: "flex", gap: 8, marginBottom: 6 }}>
                    <span style={{ color: "var(--accent-red)" }}>•</span>
                    <span style={{ fontSize: 12, color: "var(--text-secondary)" }}>{r}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </AppLayout>
  );
}
