export const mockDocuments = [
  {
    id: "d1",
    clientId: "1",
    clientName: "ABC Retail Group",
    projectId: "p1",
    type: "quote",
    title: "Quote — Black Friday Campaign 2026",
    version: "v1.2",
    status: "accepted",
    totalValue: 85000,
    currency: "ZAR",
    validUntil: "2026-07-31",
    createdAt: "2026-06-15",
    createdBy: "Jonathan",
  },
  {
    id: "d2",
    clientId: "1",
    clientName: "ABC Retail Group",
    projectId: "p1",
    type: "sow",
    title: "SOW — Black Friday Campaign 2026",
    version: "v1.0",
    status: "approved",
    totalValue: 85000,
    currency: "ZAR",
    validUntil: "2026-12-31",
    createdAt: "2026-06-20",
    createdBy: "Jonathan",
  },
  {
    id: "d3",
    clientId: "4",
    clientName: "Apex Bank Limited",
    projectId: "p3",
    type: "quote",
    title: "Quote — Digital Banking Dashboard v3",
    version: "v2.1",
    status: "sent",
    totalValue: 320000,
    currency: "ZAR",
    validUntil: "2026-07-15",
    createdAt: "2026-06-25",
    createdBy: "Jonathan",
  },
  {
    id: "d4",
    clientId: "2",
    clientName: "MedPharm SA",
    projectId: "p5",
    type: "poc",
    title: "POC — POPIA Compliance Module",
    version: "v1.0",
    status: "approved",
    totalValue: 0,
    currency: "ZAR",
    validUntil: "",
    createdAt: "2026-04-10",
    createdBy: "Jonathan",
  },
  {
    id: "d5",
    clientId: "5",
    clientName: "ConnectTel",
    projectId: "p6",
    type: "sow",
    title: "SOW — Self-Service Portal",
    version: "v1.1",
    status: "draft",
    totalValue: 145000,
    currency: "ZAR",
    validUntil: "2026-08-01",
    createdAt: "2026-06-28",
    createdBy: "Jonathan",
  },
];

export const mockCommunications = [
  {
    id: "com1",
    clientId: "1",
    clientName: "ABC Retail Group",
    type: "email",
    direction: "inbound",
    subject: "Annual Black Friday Campaign — Ready to Start",
    body: "Hi Jonathan,\n\nWe would like to kick off planning for this year's Black Friday campaign. As per last year, we'll need the full loyalty journey, email notifications, and the bulk import functionality.\n\nCould you please send us a quote and timeline?\n\nKind regards,\nSarah Mkhize\nIT Manager, ABC Retail Group",
    sender: "sarah@abcretail.co.za",
    receivedAt: "2026-06-29T09:14:00Z",
    actionRequired: true,
    actionStatus: "pending",
    projectId: "p1",
  },
  {
    id: "com2",
    clientId: "4",
    clientName: "Apex Bank Limited",
    type: "email",
    direction: "inbound",
    subject: "Dashboard Redesign — Feedback on POC",
    body: "Hi Jonathan,\n\nThe team reviewed the POC yesterday. Overall very positive — the new data visualisations are exactly what we needed.\n\nA few changes:\n1. The date range filter needs to default to the last 30 days\n2. The export button should support both Excel and PDF\n3. Mobile responsiveness needs work on the charts\n\nPlease update the SOW accordingly.\n\nThanks,\nZanele",
    sender: "z.dlamini@apexbank.co.za",
    receivedAt: "2026-06-29T08:30:00Z",
    actionRequired: true,
    actionStatus: "pending",
    projectId: "p3",
  },
  {
    id: "com3",
    clientId: "1",
    clientName: "ABC Retail Group",
    type: "meeting",
    direction: "internal",
    subject: "Quarterly Business Review — Q2 2026",
    body: "Attendees: Jonathan, Sarah Mkhize, David Nkosi\n\nDiscussion points:\n- Loyalty programme performance: 340% increase in redemptions vs Q1\n- Black Friday 2026 planning: kick off in July, campaign live by October\n- New feature request: bulk file upload with progress indicators\n- Budget approved for Q3: R180,000\n\nActions:\n- Jonathan to send Black Friday quote by 4 July\n- David to share branding assets by 7 July\n- Jonathan to schedule POC session for week of 14 July",
    sender: "jonathan@urupconnect.com",
    receivedAt: "2026-06-28T10:00:00Z",
    actionRequired: false,
    actionStatus: "completed",
    projectId: "p1",
    aiSummary: "QBR confirmed strong loyalty programme performance. Black Friday 2026 planning approved with R180,000 budget. Three action items assigned.",
  },
];

export const mockFollowUpsFull = [
  { id: "f1", clientId: "3", clientName: "FastFreight Logistics", title: "Schedule check-in call", description: "No contact in 34 days. Client is at risk.", dueDate: "2026-06-29", priority: "high", status: "pending", aiSuggested: true },
  { id: "f2", clientId: "1", clientName: "ABC Retail Group", title: "Send Black Friday SOW draft", description: "Client requested SOW following campaign kick-off email.", dueDate: "2026-07-04", priority: "high", status: "pending", aiSuggested: false },
  { id: "f3", clientId: "5", clientName: "ConnectTel", title: "Follow up on chat widget request", description: "Lungelo asked about adding a chat widget to the portal.", dueDate: "2026-07-03", priority: "medium", status: "pending", aiSuggested: false },
  { id: "f4", clientId: "4", clientName: "Apex Bank Limited", title: "Share updated dashboard wireframes", description: "Incorporate POC feedback from Zanele into updated wireframes.", dueDate: "2026-07-04", priority: "medium", status: "pending", aiSuggested: false },
  { id: "f5", clientId: "2", clientName: "MedPharm SA", title: "Confirm deployment window", description: "POPIA module approved. Confirm go-live date with Priya.", dueDate: "2026-07-01", priority: "high", status: "pending", aiSuggested: true },
  { id: "f6", clientId: "1", clientName: "ABC Retail Group", title: "Request branding assets from David", description: "David to supply logo, colour codes and banner templates.", dueDate: "2026-07-07", priority: "low", status: "pending", aiSuggested: false },
];
